<?php

namespace Config;

// Create a new instance of our RouteCollection class.
$routes = Services::routes();

/*
 * --------------------------------------------------------------------
 * Router Setup
 * --------------------------------------------------------------------
 */
$routes->setDefaultNamespace('App\Controllers');
$routes->setDefaultController('Home');
$routes->setDefaultMethod('index');
$routes->setTranslateURIDashes(false);
$routes->set404Override();
// The Auto Routing (Legacy) is very dangerous. It is easy to create vulnerable apps
// where controller filters or CSRF protection are bypassed.
// If you don't want to define all routes, please use the Auto Routing (Improved).
// Set `$autoRoutesImproved` to true in `app/Config/Feature.php` and set the following to true.
// $routes->setAutoRoute(false); // Deprecated: Use $autoRoutesImproved instead.
$routes->setAutoRoute(true); // Standard CI4 practice is often to set this to false for security and define all routes.
                             // However, for simplicity in many projects, it's left true.
                             // For this exercise, we'll keep it true but define main routes explicitly.


/*
 * --------------------------------------------------------------------
 * Route Definitions
 * --------------------------------------------------------------------
 */

// We get a performance increase by specifying the default
// route since we don't have to scan directories.
$routes->get('/', 'Home::index');

// Resource routes for application modules
// These routes are generated by the `resource` method and provide
// a RESTful interface for the controllers.

// Docente module
// Maps to DocenteController methods: index, show, new, create, edit, update, delete
$routes->resource('docentes', ['controller' => 'DocenteController']);

// Laboratorio module
// Maps to LaboratorioController methods: index, show, new, create, edit, update, delete
$routes->resource('laboratorios', ['controller' => 'LaboratorioController']);

// Reserva module
// Maps to ReservaController methods: index, show, new, create, edit, update, delete
$routes->resource('reservas', ['controller' => 'ReservaController']);


/*
 * --------------------------------------------------------------------
 * Additional Routing
 * --------------------------------------------------------------------
 *
 * There will often be times that you need additional routing and you
 * need it to be able to override any defaults in this file. Environment
 * based routes is one such time. require() additional route files here
 * to make that happen.
 *
 * You will have access to the $routes object within that file without
 * needing to reload it.
 */
if (is_file(APPPATH . 'Config/' . ENVIRONMENT . '/Routes.php')) {
    require APPPATH . 'Config/' . ENVIRONMENT . '/Routes.php';
}
